# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              DS4PS
description:        Website for the MS in Program Eval and Data Analytics Program, ASU

# Site subpath, e.g. /blog
baseurl:            "/course_website"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://hasi96.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Foundations of Data Science      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Hasitha
    github:     hasi96   # Github username for avatar


github_info:
    username:       hasi96 # Github username for avatar
    branch:       master
    website-repo:      course_website
    course-repo:        Data-Science-Class

index:
    title: Data Science
    subtitle: This course aims at empowering students especially from a non-computerscience background to learn easy tools that can be used for data analysis
    image: imac.svg


header:
- title: Course Schedule
  url: schedule/

- title: Textbook
  url: https://bookdown.org/yihui/bookdown-demo/ 

- title: Datasets
  url: datasets/

- title: Resources
  url: resources/

- title: GetHelp
  url: discussions/


footer:
- title: Home
  url: /

- title: Datasets
  url: /datasets/

- title: Textbook
  url:  https://bookdown.org/yihui/bookdown-demo/

- title: Course Syllabus
  url: /syllabus/


info: 
 program_title: MS in Program Evaluation and Data Analytics
 program_website: 
 course_title: Foundations of Data Science I
 course_number: CPP 591
 course_level: Graduate
 course_website: 
 course_start_end_dates: August 16th to December 5th
 course_prerequisites: None
 class_meets_when:  Online
 class_meets_where: MWF 5:30pm

instructor:
-  name: Benjamin M. Friedman
   title: Professor
   email: jdlecy@asu.edu
   phone:  602-123-4567
   website_url: http://www.lecy.info/
   office_hours_times: Mondays 1-3pm.
   office_hours_location:  UCENT 517
   office_hours_app_url:  https://calendly.com/
   github_url: https://github.com/
   twitter_url: https://twitter.com/
   scholar_url: https://scholar.google.com/citations?user=Ir8H4wMAAAAJ&hl=en
   linked_in_url:
-  name: Hasitha
   title:
   email:
   phone: 
   website_url:
   office_hours_times: Tuesday 12pm
   office_hours_location: 421 Central
   office_hours_app_url: https://calendly.com/
   github_url:
   twitter_url:
   scholar_url:
   linked_in_url:
-  name: Shachi
   title:
   email:
   phone: 
   website_url:
   office_hours_times: Tuesday 12pm
   office_hours_location: 421 Central
   office_hours_app_url: https://calendly.com/
   github_url:
   twitter_url:
   scholar_url:
   linked_in_url:


textbooks:
- title: Intro to Data Science
  authors: Smith, Smith, and Johnson
  edition: First Edition
  link: https://www.w3schools.com/tags/att_body_link.asp
  required (y/n): y
- title: Advanced Data Science
  authors: Yamuguchi
  edition: 
  link: https://www.w3schools.com/tags/att_body_link.asp
  required (y/n): n


# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    peter:
        name:       Peter Brown
        github:     PressApps    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/
    linkedin:
    pinterest:
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://ivanchromjak.com/">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true



course_url: "https://hasi96.github.io/Data-Science-Class/"

