# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              DS4PS
description:        Website for the MS in Program Eval and Data Analytics Program, ASU

# Site subpath, e.g. /blog
baseurl:            "/course_website"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://shachikshah.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Foundations of Data Science      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       shachi
    github:     shachikshah   # Github username for avatar


# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    peter:
        name:       Peter Brown
        github:     PressApps    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/
    linkedin:
    pinterest:
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://ivanchromjak.com/">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true

index:
    title: Data Science
    subtitle: This course aims at empowering students especially from a non-computerscience background to learn easy tools that can be used for data analysis
    image: imac.svg


header:
- title: Course Syllabus
  url: /course_website/syllabus/

- title: Textbook
  url: https://bookdown.org/yihui/bookdown-demo/ 

- title: Datasets
  url: /course_website/datasets/

- title: Resources
  url: /course_website/resources/

- title: Help
  url: /course_website/contact/

course_url: "https://hasi96.github.io/Data-Science-Class/"

info: 
 program_title: Data Science for Public Sector
 program_website: 
 course_title:
 course_number:
 course_level:
 course_website:
 course_start_end_dates:
 course_prerequisites:
 class_meets_when:
 class_meets_where:

instructor:
-  name: Jesse 
   title: Professor
   email:
   phone:
   website_url:
   office_hours_times:
   office_hours_location:
   office_hours_app_url:
   github_url: 
   twitter_url:
   scholar_url:
   linked_in_url:
-  name: Hasitha
   title:
   email:
   phone: 
   website_url:
   office_hours_times:
   office_hours_location:
   office_hours_app_url:
   github_url:
   twitter_url:
   scholar_url:
   linked_in_url:


textbooks:
- title: Intro to Data Science
  authors:
  edition:
  link: https://www.w3schools.com/tags/att_body_link.asp
  required (y/n):


footer:
- title: Home
  url: /

- title: Datasets
  url: /datasets/

- title: Textbook
  url:  https://bookdown.org/yihui/bookdown-demo/

- title: Course Timeline
  url: /syllabus/
