# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Intro to Data Science
description:        Website for the MS in Program Eval and Data Analytics Program, ASU

# Site subpath, e.g. /blog
baseurl:            "/course_website"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://hasi96.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Intro to Data Science      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Jesse Lecy
    github:     lecy   # Github username for avatar


github_info:
    username:          hasi96 # Github location of the course
    branch:            master
    website-repo:      course_website
    course-repo:       Data-Science-Class

index:
    title: Intro to Data Science for the Social Sector
    subtitle: This course introduces students to foundational tools in the field of data science.
    image: imac.svg


header:
- title: Syllabus
  url: /
  
- title: Course Schedule
  url: schedule/

- title: Textbook
  url: https://ds4ps.github.io/Data-Science-Class/01-TEXTBOOK/docs/index.html 

- title: Datasets
  url: datasets/

- title: Resources
  url: resources/

- title: Get Help
  url: discussions/


footer:
- title: Home
  url: /

- title: Datasets
  url: /datasets/

- title: Textbook
  url:  https://bookdown.org/yihui/bookdown-demo/

- title: Course Schedule
  url: /schedule/


info: 
 program_title: MS in Program Evaluation and Data Analytics
 program_website: 
 course_title: Introduction to Data Science for the Social Sector
 course_number: CPP 591
 course_level: Graduate
 course_website: 
 course_start_end_dates: Aug 16th - Dec 5th, 2018
 course_prerequisites: None
 class_meets_when:  Online
 class_meets_where: Online

instructor:
-  name: Jesse Lecy
   title: Professor
   email: jdlecy@asu.edu
   website_url: http://www.lecy.info/
   office_hours_times: Very flexible, online or in-person
   office_hours_location:  UCENT 517
   office_hours_app_url:  https://calendly.com/lecy/15min/
   github_url: https://github.com/lecy
   twitter_url: 
   scholar_url: https://scholar.google.com/citations?user=Ir8H4wMAAAAJ&hl=en
   linked_in_url:



textbooks:
- title: Big Book of Dashboards
  authors: Smith, Smith, and Johnson
  edition: First Edition
  link: https://www.amazon.com/Big-Book-Dashboards-Visualizing-Real-World/dp/1119282713/
  required (y/n): n
- title: R Cookbook
  authors: Paul Teetor
  edition: First Edition
  link: https://www.amazon.com/Cookbook-Analysis-Statistics-Graphics-Cookbooks/dp/0596809158/
  required (y/n): n


# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jesse:
        name:       Jesse Lecy
        github:     lecy    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/asupublicservice
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/asupublicservice/
    linkedin:       https://www.linkedin.com/school/asupublicservice/
    pinterest:
    twitter:        https://twitter.com/asupublicsvc
    vimeo:          
    youtube:        https://www.youtube.com/user/coppvideos

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://www.youtube.com/watch?v=WUAcN9UCnbU">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   UA-123960540-1

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: bibliography.bib
  bibliography_template: <abbr>[{{key}}]</abbr>{{reference}}

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-scholar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true



course_url: "https://hasi96.github.io/Data-Science-Class/"

